print("hello mothe fucker jeje prueba")
print(" prueba numero 1")
print("este cambio fue realizado por JB")
print("ahora añadido desde internet")
print("prueba a las 12:01")
print("prueba a las 12:03")
print("nueva prueba a las 12:04 desde VSC")